;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-smart-open-line
        crux-top-join-line
        delete-horizontal-space
        fill-paragraph
        helm-M-x
        org-end-of-line
        org-self-insert-command
        pabbrev-expand-maybe
        ))

(setq mc/cmds-to-run-once
      '(
        mark-whole-buffer
        ))
