;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-duplicate-current-line-or-region
        crux-smart-open-line
        crux-top-join-line
        delete-horizontal-space
        fill-paragraph
        haml-electric-backspace
        helm-M-x
        ignore
        kill-region
        org-delete-char
        org-end-of-line
        org-self-insert-command
        pabbrev-expand-maybe
        sp-backward-delete-char
        sp-delete-char
        text-scale-increase
        ))

(setq mc/cmds-to-run-once
      '(
        mark-whole-buffer
        markdown-exdent-or-delete
        yaml-electric-backspace
        ))
