;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        comment-dwim-2
        crux-duplicate-current-line-or-region
        crux-smart-open-line
        crux-top-join-line
        delete-horizontal-space
        easy-kill
        end-of-visual-line
        fastnav-zap-up-to-char-forward
        fill-paragraph
        haml-electric-backspace
        handle-switch-frame
        helm-M-x
        iedit-mode
        ignore
        kill-region
        mac-mwheel-scroll
        org-delete-char
        org-end-of-line
        org-return-indent
        org-self-insert-command
        pabbrev-expand-maybe
        sh-assignment
        sp-backward-delete-char
        sp-delete-char
        text-scale-increase
        typescript-insert-and-indent
        web-mode-element-clone
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-switch-to-mc-mode
        mark-whole-buffer
        markdown-exdent-or-delete
        markdown-outdent-or-delete
        yaml-electric-backspace
        ))
